import boto3
from botocore.exceptions import NoCredentialsError, PartialCredentialsError, ClientError
import os

def upload_to_s3(file_name, bucket, object_name=None):
    """
    Upload a file to an S3 bucket.

    :param file_name: File to upload
    :param bucket: Bucket to upload to
    :param object_name: S3 object name. If not specified, file_name is used
    :return: True if file was uploaded, else False
    """
    # If S3 object_name was not specified, use file_name
    if object_name is None:
        object_name = os.path.basename(file_name)

    # Create an S3 client
    s3_client = boto3.client('s3')

    try:
        print(f"Uploading {file_name} to bucket {bucket} as {object_name}...")
        response = s3_client.upload_file(file_name, bucket, object_name)
        print("Upload Successful.")
        return True
    except FileNotFoundError:
        print(f"Error: The file {file_name} was not found.")
        return False
    except (NoCredentialsError, PartialCredentialsError):
        print("Error: AWS credentials not found.")
        print("Please configure your credentials by running 'aws configure'")
        return False
    except ClientError as e:
        # Handle specific client errors, like bucket not found
        if e.response['Error']['Code'] == 'NoSuchBucket':
            print(f"Error: The bucket '{bucket}' does not exist.")
        else:
            print(f"An S3 client error occurred: {e}")
        return False
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        return False

def main():
    """Main function to handle the S3 upload process."""
    # --- Configuration ---
    # The local file generated by the first script.
    local_file_to_upload = 'financial_news_with_text.csv'
    
    # The name of your S3 bucket.
    s3_bucket_name = 'your-unique-bucket-name' # <-- IMPORTANT: Change this!
    
    # The name you want the file to have in S3.
    s3_object_name = 'processed/financial_news_with_text.csv'

    # Check if the local file exists before attempting to upload
    if not os.path.exists(local_file_to_upload):
        print(f"Error: Cannot find the local file '{local_file_to_upload}'.")
        print("Please run the 'scrape_news.py' script first to generate it.")
        return
        
    if s3_bucket_name == 'your-unique-bucket-name':
        print("Please update the 's3_bucket_name' variable in the script with your actual S3 bucket name.")
        return

    # Upload the file
    upload_to_s3(local_file_to_upload, s3_bucket_name, s3_object_name)

if __name__ == "__main__":
    # Ensure you have boto3 installed:
    # pip install boto3
    main()
